yay -S locale-en_xx
yay -S python-plumbum
yay -S python-pytz
yay -S python-pip
yay -S psutils
yay -S qtile-git
yay -S qtile-git
yay -S python
yay -S ipython
yay -S python-psutil
yay -S emacs
yay -S rofi
yay -S deezer
yay -S notmuch
yay -S htop
yay -S slack
yay -S clipmenu
yay -S clipmenu
yay -S xdotool
yay -S blueman-git
yay -S bluedevil
yay -S blueman
yay -S bluetoothctl
yay -S bluez
yay -S bluez-utils
yay -S surf
yay -S locale-en_xx
yay -S python-plumbum
yay -S python-pytz
yay -S python-pip
yay -S psutils
yay -S qtile-git
yay -S ipython
yay -S python-psutil
yay -S htop
yay -S slack
yay -S xdotool
yay -S blueman
yay -S bluetoothctl
yay -S bluez
yay -S bluez-utils
yay -S python-dateutil
yay -S python-ipdb
yay -S slack-desktop fortune-mod-all-en
yay -S patch
yay -S python-mpd2
yay -S python-iwlib
yay -S python-keyring
yay -S python-xdg
yay -S pactl
yay -S pavucontrol
yay -S amixer
yay -S alsamixer
yay -S qt5-webengine
yay -S python-pyqtwebengine
yay -S manpath
yay -S man-db
yay -S pass
yay -S pinentry-dmenu
yay -S avahi
yay -S ttf-liberation
yay -S glxgears
yay -S mesa-demos
yay -S nvidiuname -a
yay -S lib32-nvidia-utils
yay -S python-gpustat
yay -S gmonitor
yay -S xcb-cursor
yay -S xcb-util
yay -S xcb-util-cursor
yay -S mlocate
yay -S dmenu2
yay -S clipmenu
yay -S autoreconf
yay -S autoconf
yay -S automake
yay -S inconsolata-psf-git
yay -S ttf-inconsolata
yay -S python-notify2
yay -S dmidecode
yay -S cpuinfo
yay -S ttf-terminus
yay -S terminus-font
yay -S terminus-font-ttf
yay -S cpu-checker
yay -S axel
yay -S salt
yay -S 'salt'
yay -S Xpra
yay -S powetop
yay -S powertop
yay -S wget
yay -S dnsmasq
yay -S polkit
yay -S pigz
yay -S geniso
yay -S cdrtools
yay -S virsh
yay -S salt-py3
yay -S sudo
yay -S 'sudo'
yay -S silver-searcher-git
yay -S the_silver_searcher
yay -Si bluedevil
yay -S mc
yay -S 'mc'
yay -S pico
yay -S bluez-hciconfig
yay -S hcitool
yay -S bluez-hcitool
yay -S usb_modeswitch
yay -S peco
yay -S bridge-utils
yay -S iproute2
yay -S plantuml
yay -S python-pipenv
yay -S gdal
yay -S -y gdal
yay -S torbrowser-launcher
yay -S dis
yay -S genius
yay -S stern
yay -S stern-bin
yay -S -y erlang
yay -S usbmuxd
yay -S ipwndfu-linushenze-git
yay -S dropbox
yay -S dmenu
yay -S tor
yay -S tor-browser
yay -S most
yay -S electrum
yay -S -y electrum
yay -S spectacle
yay -S -y spectacle
yay -S autossh
yay -S android-tools
yay -S dot
yay -S imagemagick
yay -S graphviz
yay -S redis
yay -S android-studio
yay -S flake8
yay -S python-pbr
yay -S fluxctl
yay -S kerl
yay -S ebtables
yay -S ovmf
yay -S qemu
yay -S -y qemu
yay -S virt-manager-git
yay -S looking-glass
yay -S pulseaudio-bluetooth
yay -S alsa-utils
yay -S pulseaudio-modules-bt
yay -S -y pulseaudio-modules-bt
yay -S libldac
yay -S -c bluez-utils-compat
yay -S bluez-utils-compat
yay -S -y linux-lts
yay -S seabios
yay -S qemu-kvm
yay -S lshw
yay -S nvidia-settings
yay -S kdesu
yay -S -y kdesu
yay -S snapd
yay -S kustomize-bin
yay -S vbetool
yay -S postgresql
yay -S -y postgresql
yay -S helm-bin
yay -S kubernetes-helmfile-bin
yay -Si privoxy
yay -S pgbouncer
yay -S erlang
yay -S rebar
yay -S rebar3-git
yay -S rabbitmq
yay -S alsa-plugins
yay -S libmpeg2 q
yay -S libmpeg2
yay -Si firefox
yay -S mplayer
yay -S gstreamer
yay -S gstreamer0.10-bad-plugins
yay -S gstreamer0.10-bad
yay -S nvidia
yay -S gst
yay -S slim
yay -S postgis
yay -S netcat
yay -S nvidiux
yay -S xpra
yay -S nginx
yay -S -y ngin
yay -S -y nginx
yay -S rebar3
yay -S -y
yay -S pdftoppm
yay -S poppler
yay -S feh
yay -S -y feh
yay -S filelight
yay -S monero-gui
yay -S google-chrome
yay -S -y google-chrome
yay -S teams
yay -S pwgen
yay -S transmission
yay -S transmission-cli
yay -S fbset
yay -S packagekit
yay -S cockpit-docker
yay -S cockpit-dashboard
yay -S cockpit-zfs-manager
yay -S virt-install
yay -S qemu-block-gluster fixed
yay -S qemu-block-gluster
yay -S pam-krb5
yay -S nvflash
yay -Si steam-appmanifest-git
yay -S systemsettings
yay -S sddm-archlinux-theme-git
yay -S slim-archlinux-solarized-spiral
yay -S tzupdate
yay -S rng-tools
yay -S amd-ucode
yay -S cpu-g
yay -S hardinfo
yay -S kedit
yay -S python-pllint
yay -S python-flake8
yay -S python-flake8-coding
yay -S python-flake8-builtins
yay -S python-pylint-plugin-utils
yay -S python-bluepy
yay -S steam-clik
yay -S steam-cli
yay -S SteamCMD
yay -S python-pybluez
yay -S python-pyqt5
yay -S python-dbus
yay -S python-pydbus
yay -S python-apscheduler
yay -S nss-mdns
yay -S prometheus-node-exporter-bin
yay -S prometheus-node-exporter
yay -S golang
yay -S nvidia-utils
yay -S python-py3nvml
yay -S cud
yay -S opencl-nvidia
yay -S cuda
yay -S nvidia-exporter-git
yay -S coert
yay -S cower
yay -S lm_sensors
yay -S -y cockpit
yay -S -y cockpit-git
yay -S cockpit-git
yay -S skill
yay -S nmap
yay -S -y nmap
yay -S lutris
yay -S -y lutris
yay -S wine
yay -S winetricks
yay -S wine-gecko
yay -S wine-mono
yay -S lib32-gnutls lib32-libldap lib32-libgpg-error lib32-libxml2 lib32-alsa-plugins lib32-sdl2 lib32-freetype2 lib32-dbus lib32-libgcrypt libgcrypt
yay -S -y lib32-gnutls lib32-libldap lib32-libgpg-error lib32-libxml2 lib32-alsa-plugins lib32-sdl2 lib32-freetype2 lib32-dbus lib32-libgcrypt libgcrypt
yay -S fontconfig
yay -S fontconfig-ubuntu
yay -S -y qtwebflix-git
yay -S emacs
yay -S -y emacs
yay -S xcompmgr
yay -S kmix
yay -S -y kmix
yay -S mictray
yay -S nc-pamixer-git
yay -S ncpamixer-git
yay -S pamixer
yay -S PAmix
yay -S pamix
yay -S pamix-git
yay -S dolphin
yay -S brotab
yay -S hunspell
yay -S reflector
yay -S spotify-cli
yay -S spotifyd
yay -S alsa-firmware
yay -S qemu-guest-agent
yay -S -y qemu-guest-agent
yay -S hunspell-en_AU
yay -S bitwarden-dmenu
yay -S bitwarden-cli
yay -S bitwarden-cli-bin
yay -S tensorflow
yay -S gitlab-runner
yay -S kubernetes-bin
yay -S -y chromium
yay -S git-lfs
yay -S python-boto
yay -S rofi
yay -S rofi-blocks-git
yay -S aws-cli
yay -S iw
yay -S linux-firmware
yay -S devpi-client
yay -S python-poetry
yay -S kdebase-runtime
yay -S openvslam
yay -S eigen3-hg
yay -S eigen
yay -S ros-kinetic-robot
yay -S ros-noetic-desktop-full
yay -S -y ros-noetic-desktop-full
yay -Si mpd
yay -S mopidy
yay -S cantata
yay -S mopidy-spotify
yay -S byzanz
yay -S zoom
yay -S qutebrowser
yay -S i3
yay -S wavebox
yay -S ppgrep
yay -S pgrep
yay -S vl4ucp
yay -S v4l2ucp
yay -S docker
yay -S runc
yay -S containerd
yay -S discord
yay -S python-pylint
yay -S gmail-destop
yay -S gmail-desktop
yay -S rg
yay -S ripgrep
yay -Si mimeo
yay -S cpupower
yay -S cockpit
yay -S cockpit-machines
yay -S polip
yay -S polipo
yay -S notmuch
yay -S squid
yay -S virt-viewer
yay -S libvirt
yay -S virt-manager
yay -S -y virt-manager
yay -S qt5ct
yay -S oxygen
yay -S oxygencolors
yay -S oxygen-icons
yay -S breeze-icons
yay -S asp
yay -S surf
yay -S gcr
yay -S gwe
yay -S -y gwe
yay -S -y |grep xcomp
yay -S fd
yay -S markdown_previewer
yay -S markdown
yay -S nixfmt
yay -Sps_proxy= pmi nixfmt
yay -S nix
yay -Sps_proxy= pmi nix
yay -Sps_proxy= pmi nix-bin
yay -S aspell-en
yay -S aspell
yay -S aspell-uk
yay -S aspell-us
yay -S libguestfs
yay -S -y libguestfs
yay -S smartctl
yay -S smartmontools
yay -S inotify-tools
yay -S ga-cmd
yay -S peek
yay -S silentcast
yay -S sshtunnel
yay -S python
yay -S -y python
yay -S docker-compose
yay -S -y docker-compose
yay -S -y python-pip
yay -S -y python-setuptools
yay -S dif
yay -S dig
yay -S whatsapp-nativefier
yay -S chromium
yay -S spotify
yay -S kubectl-bin
yay -S obs-studio
yay -S xdg-user-dirs
yay -S xdg-utils
yay -S xdg-utils-mimeo
yay -S openshot
yay -S -y nvidia-lts
yay -S nvidia-lts
yay -S screenkeys
yay -S screenkey
yay -S slack-desktop
yay -S pinentry-curses
yay -S pinentry
yay -S pscd
yay -S pcscd
yay -S pcsc-tools
yay -S -y slack-desktop
yay -S xorg-server
yay -S dunst
yay -S gnupg
yay -S pinentry-qt
yay -S opencl-mesa
yay -S xf86-video-amdgpu
yay -S -yu
yay -S linux-lts
yay -S amdgpu-lts
yay -S xf86-video-ati
yay -S xorg-xinit
yay -S mesa
yay -S unixpass
yay -S pass
yay -S peco
yay -S python-plumbum
yay -S python-pytz
yay -S bluez-utils
yay -S clipmenu
yay -S xdotool
yay -S pacmd
yay -S pulseaudio
yay -S dunst
yay -S notify-osd
yay -S libnotify
yay -S python-psutil
yay -S tzupdate
