yay -S locale-en_xx
yay -S python-plumbum
yay -S python-pytz
yay -S python-pip
yay -S psutils
yay -S qtile-git
yay -S qtile-git
yay -S python
yay -S ipython
yay -S python-psutil
yay -S emacs
yay -S rofi
yay -S deezer
yay -S notmuch
yay -S htop
yay -S slack
yay -S clipmenu
yay -S clipmenu
yay -S xdotool
yay -S blueman-git
yay -S bluedevil
yay -S blueman
yay -S bluetoothctl
yay -S bluez
yay -S bluez-utils
yay -S surf
